### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by oppianmatt** [jakul/python-transifex#25]
```
Executing pull_translations on project pitchupcom
Pulling translations for "pitchupcom" project, in "en_GB" source language
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/pitchup/campsite/management/commands/tx.py", line 80, in handle
    command_func(*args[1:], **options)
  File "/app/pitchup/campsite/management/commands/tx.py", line 164, in transifex_pull_translations
    project_slug=self.project_slug, source_language=self.source_language
  File "/app/lib/djangotransifex/api.py", line 157, in pull_translations
    resources = self.list_resources(project_slug)
  File "/usr/local/lib/python2.7/site-packages/transifex/api.py", line 106, in list_resources
    return json.loads(response.content)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Using it in django-transifex but error is in here.

the response.content is no longer json encoded

![image](https://user-images.githubusercontent.com/48596/32058259-75d5bab8-ba61-11e7-8b16-362b1100569f.png)

according to the response headers it's python pickle format

![image](https://user-images.githubusercontent.com/48596/32058293-88cadca2-ba61-11e7-9d7b-5f4b551fac15.png)

My guess is that the request headers which by default set to accept */* and a user agent of python-requests cause their api to issue a different format in response.

![image](https://user-images.githubusercontent.com/48596/32058373-ba65f30a-ba61-11e7-8431-7b4e8c9f1ff5.png)

**Comment by oppianmatt** [comment]
Here it is in a console:

```
In [1]: from transifex.api import TransifexAPI

In [2]: t = TransifexAPI('xxx', 'xxx', 'https://www.transifex.com')

In [3]: t.ping()
Out[3]: True

In [4]: t.list_resources('pitchupcom')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-634ee222c819> in <module>()
----> 1 t.list_resources('pitchupcom')

/usr/local/lib/python2.7/site-packages/transifex/api.pyc in list_resources(self, project_slug)
    104             raise TransifexAPIException(response)
    105
--> 106         return json.loads(response.content)
    107
    108     def new_resource(self, project_slug, path_to_pofile, resource_slug=None,

/usr/local/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    337             parse_int is None and parse_float is None and
    338             parse_constant is None and object_pairs_hook is None and not kw):
--> 339         return _default_decoder.decode(s)
    340     if cls is None:
    341         cls = JSONDecoder

/usr/local/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
    362
    363         """
--> 364         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    365         end = _w(s, end).end()
    366         if end != len(s):

/usr/local/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
    380             obj, end = self.scan_once(s, idx)
    381         except StopIteration:
--> 382             raise ValueError("No JSON object could be decoded")
    383         return obj, end

ValueError: No JSON object could be decoded
```
